"""Central path configuration for MetricGuard AI.

Single source of truth for where data lives and where pipeline outputs go, so
no module hardcodes or re-derives these paths independently. Every path here
is computed relative to the project root, never absolute.

``quality_checks.py`` re-exports :data:`DATA_DIR` (it owns table loading), and
every other ``src/`` module imports ``DATA_DIR`` from ``quality_checks`` rather
than from here directly, to keep one canonical import path. New code should
prefer importing directly from this module.

Two dataset sizes (amendment A10, .ai/PROJECT_SPEC.md Section 13):

``full``
    The complete dataset, CSV, in :data:`FULL_DATA_DIR` (gitignored — too
    large to commit; regenerate with ``python src/generate_synthetic_data.py
    --size full`` or ``make data``).
``sample``
    A small deterministic subset, Parquet, in :data:`SAMPLE_DATA_DIR`
    (committed, under 10 MB total; regenerate with ``--size demo`` or
    ``make data-demo``).

The ``METRICGUARD_DATA`` environment variable selects between them
(``full`` or ``sample``). Unset: use full data when present, otherwise fall
back to sample. This selection is read once, at import time — set the
environment variable before starting the process (script or ``streamlit
run``), not while it's running. :data:`DATASET_SIZE` and
:data:`ACTIVE_DATA_DIR` record what was actually selected, so the pipeline
and the app can both report it.

``metric_definitions.csv`` is metadata (a KPI catalog), not data that scales
with dataset size, so it is never duplicated into ``data/sample/``: both
sizes read it from the single location :data:`METRIC_DEFINITIONS_PATH`.
"""

from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Full-size synthetic source tables (CSV), gitignored except for
# metric_definitions.csv (see METRIC_DEFINITIONS_PATH below).
FULL_DATA_DIR = PROJECT_ROOT / "data" / "synthetic"

# Demo-size synthetic source tables (Parquet), committed, under 10 MB total.
SAMPLE_DATA_DIR = PROJECT_ROOT / "data" / "sample"

# Single shared location for the KPI catalog, used by both dataset sizes.
METRIC_DEFINITIONS_PATH = FULL_DATA_DIR / "metric_definitions.csv"

_ENV_VAR = "METRICGUARD_DATA"
_choice = os.environ.get(_ENV_VAR, "").strip().lower()
if _choice in ("full", "sample"):
    DATASET_SIZE = _choice
elif _choice:
    raise ValueError(f"{_ENV_VAR} must be 'full' or 'sample' (or unset), got {_choice!r}")
else:
    # Unset: prefer full data when it has actually been generated, otherwise
    # fall back to the committed sample so the pipeline/app still run.
    DATASET_SIZE = "full" if (FULL_DATA_DIR / "transactions.csv").exists() else "sample"

ACTIVE_DATA_DIR = FULL_DATA_DIR if DATASET_SIZE == "full" else SAMPLE_DATA_DIR

# Backward-compatible name: every module that does `data_dir: Path = DATA_DIR`
# follows METRICGUARD_DATA automatically through this one import.
DATA_DIR = ACTIVE_DATA_DIR

# Where src/run_pipeline.py writes its run artifacts. Gitignored: these are
# regenerated by running the pipeline, never hand-edited or committed.
OUTPUT_DIR = PROJECT_ROOT / "outputs"

# Methodology, data dictionary, ground truth, KPI research (amendment A12/CC5:
# docs/ground_truth.md; the six design docs formerly at the repo root also
# live here now).
DOCS_DIR = PROJECT_ROOT / "docs"
