"""Central path configuration for MetricGuard AI.

Single source of truth for where data lives and where pipeline outputs go, so
no module hardcodes or re-derives these paths independently. Every path here
is computed relative to the project root, never absolute.

``quality_checks.py`` re-exports :data:`DATA_DIR` (it owns table loading), and
every other ``src/`` module imports ``DATA_DIR`` from ``quality_checks`` rather
than from here directly, to keep one canonical import path. New code should
prefer importing directly from this module.
"""

from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Full-size synthetic source tables, committed for this stage of the project.
DATA_DIR = PROJECT_ROOT / "data" / "synthetic"

# Where src/run_pipeline.py writes its run artifacts. Gitignored: these are
# regenerated by running the pipeline, never hand-edited or committed.
OUTPUT_DIR = PROJECT_ROOT / "outputs"
