"""Single entry point for the MetricGuard AI pipeline.

Runs every stage in order against the full synthetic dataset, on the same
in-memory tables (loaded once), prints the headline numbers, and writes each
stage's key result frames to :data:`config.OUTPUT_DIR` (gitignored — these are
regenerated by running this script, never hand-edited or committed).

    quality checks -> metric (raw vs. corrected) -> drivers -> complaint
    themes -> action plan -> explanation (no API key required)

Run with::

    python src/run_pipeline.py

or via ``make pipeline``.
"""

from __future__ import annotations

import time
from pathlib import Path

import pandas as pd

from action_engine import build_action_plan
from config import OUTPUT_DIR
from driver_analysis import build_driver_report
from explanation_engine import build_evidence_packet, explain
from metric_engine import build_finance_metric_report, build_metric_report
from quality_checks import load_tables, run_quality_checks, summarize_quality_checks
from text_theme_analysis import build_text_theme_report


def _write_csv(frame: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, index=False)


def run_pipeline(output_dir: Path = OUTPUT_DIR) -> dict[str, object]:
    """Run every pipeline stage once and write its outputs. Returns the headline facts."""
    started = time.perf_counter()

    tables = load_tables()

    quality_report = run_quality_checks(tables=tables)
    quality_summary = summarize_quality_checks(quality_report)

    metric_report = build_metric_report(tables=tables)
    finance_metric_report = build_finance_metric_report("dispute_rate", tables)

    driver_report = build_driver_report(tables=tables)
    theme_report = build_text_theme_report(tables=tables)

    action_plan = build_action_plan(
        finance_metric_report, quality_report, driver_report, theme_report
    )

    evidence = build_evidence_packet(
        metric_report=metric_report,
        quality_report=quality_report,
        driver_report=driver_report,
        theme_report=theme_report,
    )
    explanation = explain(evidence)

    output_dir.mkdir(parents=True, exist_ok=True)
    _write_csv(metric_report.monthly_trend, output_dir / "metric_monthly_trend.csv")
    _write_csv(metric_report.period_comparison, output_dir / "metric_period_comparison.csv")
    _write_csv(metric_report.remediation_impact, output_dir / "metric_remediation_impact.csv")
    _write_csv(quality_report, output_dir / "quality_checks.csv")
    _write_csv(driver_report.segment_drivers, output_dir / "driver_segment_drivers.csv")
    _write_csv(driver_report.top_count_drivers, output_dir / "driver_top_count_drivers.csv")
    _write_csv(theme_report.theme_summary, output_dir / "theme_summary.csv")
    _write_csv(action_plan.recommendations, output_dir / "action_recommendations.csv")
    (output_dir / "explanation.md").write_text(explanation.to_markdown(), encoding="utf-8")

    elapsed = time.perf_counter() - started

    remediation = metric_report.remediation_impact.iloc[0]
    comparison = metric_report.period_comparison.set_index("variant")
    top_driver = driver_report.top_count_drivers.iloc[0]

    return {
        "current_period": metric_report.current_period,
        "previous_period": metric_report.previous_period,
        "raw_previous_value": float(comparison.loc["raw", "previous_value"]),
        "raw_current_value": float(comparison.loc["raw", "current_value"]),
        "raw_percent_change": float(comparison.loc["raw", "percent_change"]),
        "corrected_previous_value": float(comparison.loc["corrected", "previous_value"]),
        "corrected_current_value": float(comparison.loc["corrected", "current_value"]),
        "corrected_percent_change": float(comparison.loc["corrected", "percent_change"]),
        "duplicate_disputed_rows_removed": int(remediation["duplicate_disputed_rows_removed"]),
        "duplicate_purchase_rows_removed": int(remediation["duplicate_purchase_rows_removed"]),
        "top_driver_segment": top_driver["segment_name"],
        "top_driver_value": top_driver["segment_value"],
        "top_driver_contribution_share": float(
            top_driver["contribution_share_of_positive_dispute_change"]
        ),
        "quality_checks_total": quality_summary["total_checks"],
        "quality_checks_passed": quality_summary["passed"],
        "quality_checks_warned": quality_summary["warned"],
        "quality_checks_failed": quality_summary["failed"],
        "explanation_generated_by": explanation.generated_by,
        "explanation_numbers_checked": len(explanation.validation.checked),
        "explanation_numbers_unsupported": len(explanation.validation.unsupported),
        "elapsed_seconds": elapsed,
        "output_dir": str(output_dir),
    }


if __name__ == "__main__":
    facts = run_pipeline()

    print(f"MetricGuard AI pipeline — {facts['current_period']} vs {facts['previous_period']}")
    print("=" * 100)
    print(
        f"Raw dispute rate:       {facts['raw_previous_value']:.4%} -> "
        f"{facts['raw_current_value']:.4%}  ({facts['raw_percent_change']:+.4%})"
    )
    print(
        f"Corrected dispute rate: {facts['corrected_previous_value']:.4%} -> "
        f"{facts['corrected_current_value']:.4%}  ({facts['corrected_percent_change']:+.4%})"
    )
    print(
        f"Duplicate disputed purchase rows removed: {facts['duplicate_disputed_rows_removed']} "
        f"(of {facts['duplicate_purchase_rows_removed']} duplicate purchase rows)"
    )
    print(
        f"Top driver: {facts['top_driver_segment']} = {facts['top_driver_value']} "
        f"({facts['top_driver_contribution_share']:.2%} of the positive dispute change)"
    )
    print(
        f"Data quality: {facts['quality_checks_passed']}/{facts['quality_checks_total']} passed, "
        f"{facts['quality_checks_warned']} warned, {facts['quality_checks_failed']} failed"
    )
    print(
        f"Explanation: generated_by={facts['explanation_generated_by']}, "
        f"{facts['explanation_numbers_checked']} numbers checked, "
        f"{facts['explanation_numbers_unsupported']} unsupported"
    )
    print(f"Elapsed: {facts['elapsed_seconds']:.1f}s")
    print(f"Outputs written to: {facts['output_dir']}")
