"""Single entry point for the MetricGuard AI pipeline.

Runs every stage in order against the full synthetic dataset, on the same
in-memory tables (loaded once), prints the headline numbers, and writes every
report frame the standalone modules produce to :data:`config.OUTPUT_DIR`
(gitignored — these are regenerated by running this script, never hand-edited
or committed).

    quality checks -> metric (raw vs. corrected) -> drivers -> complaint
    themes -> action plan -> explanation (no API key required)

Run with::

    python src/run_pipeline.py

or via ``make pipeline``.
"""

from __future__ import annotations

import time
from pathlib import Path

import pandas as pd

from action_engine import build_action_plan
from config import ACTIVE_DATA_DIR, DATASET_SIZE, OUTPUT_DIR
from driver_analysis import build_driver_report
from explanation_engine import build_evidence_packet, explain
from metric_engine import build_finance_metric_report, build_metric_report
from quality_checks import load_tables, run_quality_checks, summarize_quality_checks
from text_theme_analysis import build_text_theme_report


def _write_csv(frame: pd.DataFrame, path: Path, written: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, index=False)
    written.append(path)


def _write_markdown(text: str, path: Path, written: list[Path]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    written.append(path)


def run_pipeline(output_dir: Path = OUTPUT_DIR) -> dict[str, object]:
    """Run every pipeline stage once and write its outputs. Returns the headline facts."""
    started = time.perf_counter()

    tables = load_tables()

    quality_report = run_quality_checks(tables=tables)
    quality_summary = summarize_quality_checks(quality_report)

    metric_report = build_metric_report(tables=tables)
    finance_metric_report = build_finance_metric_report("dispute_rate", tables)

    driver_report = build_driver_report(tables=tables)
    theme_report = build_text_theme_report(tables=tables)

    action_plan = build_action_plan(
        finance_metric_report, quality_report, driver_report, theme_report
    )

    evidence = build_evidence_packet(
        metric_report=metric_report,
        quality_report=quality_report,
        driver_report=driver_report,
        theme_report=theme_report,
    )
    explanation = explain(evidence)

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    skipped: list[str] = []

    # --- metric (raw vs. corrected dispute rate) ---------------------------
    _write_csv(metric_report.monthly_trend, output_dir / "metric_monthly_trend.csv", written)
    _write_csv(metric_report.period_comparison, output_dir / "metric_period_comparison.csv", written)
    _write_csv(metric_report.remediation_impact, output_dir / "metric_remediation_impact.csv", written)

    # --- data quality --------------------------------------------------------
    _write_csv(quality_report, output_dir / "quality_checks.csv", written)

    # --- drivers ---------------------------------------------------------------
    _write_csv(driver_report.segment_drivers, output_dir / "driver_segment_drivers.csv", written)
    _write_csv(driver_report.top_count_drivers, output_dir / "driver_top_count_drivers.csv", written)
    _write_csv(
        driver_report.top_rate_deterioration, output_dir / "driver_top_rate_deterioration.csv", written
    )
    _write_csv(
        driver_report.interaction_heatmap_data,
        output_dir / "driver_interaction_heatmap.csv",
        written,
    )
    if driver_report.decision_tree_rules is None:
        skipped.append("driver_decision_tree_rules.csv (scikit-learn not installed)")
    else:
        _write_csv(
            driver_report.decision_tree_rules,
            output_dir / "driver_decision_tree_rules.csv",
            written,
        )

    # --- complaint themes -----------------------------------------------------
    _write_csv(theme_report.theme_summary, output_dir / "theme_summary.csv", written)
    _write_csv(theme_report.segment_themes, output_dir / "theme_segment_themes.csv", written)
    _write_csv(
        theme_report.representative_complaints,
        output_dir / "theme_representative_complaints.csv",
        written,
    )
    if theme_report.emerging_clusters is None:
        skipped.append("theme_emerging_clusters.csv (scikit-learn not installed)")
    else:
        _write_csv(
            theme_report.emerging_clusters, output_dir / "theme_emerging_clusters.csv", written
        )

    # --- action plan -------------------------------------------------------
    _write_csv(action_plan.recommendations, output_dir / "action_recommendations.csv", written)
    _write_csv(action_plan.scenario_analysis, output_dir / "action_scenario_analysis.csv", written)
    _write_csv(action_plan.scorecard, output_dir / "action_scorecard.csv", written)
    action_plan_text = (
        f"# Action plan — {action_plan.display_name} "
        f"({action_plan.current_period} vs {action_plan.previous_period})\n\n"
        f"{action_plan.decision_summary}\n\n"
        "## Methodology\n\n"
        + "\n".join(f"- {step}" for step in action_plan.methodology)
        + "\n"
    )
    _write_markdown(action_plan_text, output_dir / "action_plan.md", written)

    # --- explanation ---------------------------------------------------------
    _write_markdown(explanation.to_markdown(), output_dir / "explanation.md", written)

    elapsed = time.perf_counter() - started

    remediation = metric_report.remediation_impact.iloc[0]
    comparison = metric_report.period_comparison.set_index("variant")
    top_driver = driver_report.top_count_drivers.iloc[0]

    return {
        "dataset_size": DATASET_SIZE,
        "dataset_dir": str(ACTIVE_DATA_DIR),
        "current_period": metric_report.current_period,
        "previous_period": metric_report.previous_period,
        "raw_previous_value": float(comparison.loc["raw", "previous_value"]),
        "raw_current_value": float(comparison.loc["raw", "current_value"]),
        "raw_percent_change": float(comparison.loc["raw", "percent_change"]),
        "corrected_previous_value": float(comparison.loc["corrected", "previous_value"]),
        "corrected_current_value": float(comparison.loc["corrected", "current_value"]),
        "corrected_percent_change": float(comparison.loc["corrected", "percent_change"]),
        "duplicate_disputed_rows_removed": int(remediation["duplicate_disputed_rows_removed"]),
        "duplicate_purchase_rows_removed": int(remediation["duplicate_purchase_rows_removed"]),
        "top_driver_segment": top_driver["segment_name"],
        "top_driver_value": top_driver["segment_value"],
        "top_driver_contribution_share": float(
            top_driver["contribution_share_of_positive_dispute_change"]
        ),
        "quality_checks_total": quality_summary["total_checks"],
        "quality_checks_passed": quality_summary["passed"],
        "quality_checks_warned": quality_summary["warned"],
        "quality_checks_failed": quality_summary["failed"],
        "explanation_generated_by": explanation.generated_by,
        "explanation_numbers_checked": len(explanation.validation.checked),
        "explanation_numbers_unsupported": len(explanation.validation.unsupported),
        "elapsed_seconds": elapsed,
        "output_dir": str(output_dir),
        "files_written": written,
        "files_skipped": skipped,
    }


if __name__ == "__main__":
    facts = run_pipeline()

    print(f"MetricGuard AI pipeline — {facts['current_period']} vs {facts['previous_period']}")
    print(f"Dataset: {facts['dataset_size']} ({facts['dataset_dir']})")
    print("=" * 100)
    print(
        f"Raw dispute rate:       {facts['raw_previous_value']:.4%} -> "
        f"{facts['raw_current_value']:.4%}  ({facts['raw_percent_change']:+.4%})"
    )
    print(
        f"Corrected dispute rate: {facts['corrected_previous_value']:.4%} -> "
        f"{facts['corrected_current_value']:.4%}  ({facts['corrected_percent_change']:+.4%})"
    )
    print(
        f"Duplicate disputed purchase rows removed: {facts['duplicate_disputed_rows_removed']} "
        f"(of {facts['duplicate_purchase_rows_removed']} duplicate purchase rows)"
    )
    print(
        f"Top driver: {facts['top_driver_segment']} = {facts['top_driver_value']} "
        f"({facts['top_driver_contribution_share']:.2%} of the positive dispute change)"
    )
    print(
        f"Data quality: {facts['quality_checks_passed']}/{facts['quality_checks_total']} passed, "
        f"{facts['quality_checks_warned']} warned, {facts['quality_checks_failed']} failed"
    )
    print(
        f"Explanation: generated_by={facts['explanation_generated_by']}, "
        f"{facts['explanation_numbers_checked']} numbers checked, "
        f"{facts['explanation_numbers_unsupported']} unsupported"
    )
    print(f"Elapsed: {facts['elapsed_seconds']:.1f}s")
    print()
    print(f"Wrote {len(facts['files_written'])} files to {facts['output_dir']}:")
    for path in facts["files_written"]:
        print(f"  - {Path(path).name}")
    if facts["files_skipped"]:
        print("Skipped:")
        for reason in facts["files_skipped"]:
            print(f"  - {reason}")
